### ISSUE TITLE
on nuxt generate (npm run generate) error on image from another domain. images from assets folder work good.

### ISSUE THREAD

**Issue by Mansurkhoja** [nuxt/image#1110]
![sc1](https://github.com/nuxt/image/assets/68527235/eac3e9ec-13fe-4777-bce4-26ad09f4d356)

**Comment by Mansurkhoja** [comment]
@jdempster

**Comment by kamilmedrala** [comment]
I had the same issue.
The problem seems to be with colon in 'https:'  in path after mkdir. My workaround was to set an alias in nuxt.config.
https://image.nuxt.com/get-started/configuration#alias

In your case it should look something like this:
nuxt.config.js:
```
image:{
  ...
  domains: ['ralphlauren.com'],
  alias: {
     rl: "https://www.ralphlauren.com/"
  }
}
```

then in nuxt-img component you can do something like:
```
:src="imageSrc.replace('https://www.ralphlauren.com/','/rl/')"
```

**Comment by Mansurkhoja** [comment]
Cool thx, bro)) but why in nuxt-image docs except about it?((

**Comment by Mansurkhoja** [comment]
))
