### ISSUE TITLE
Just don't work

### ISSUE THREAD

**Issue by wireinet** [nuxt/image#1262]
I just can't make this work...
install, add module, restart server, get error:
[worker reload] [worker init] Cannot find package 'ipx' imported from D:\......\.nuxt\dev\index.mjs
just default setup: no option in 'defineNuxtConfig'

**Comment by gbyesiltas** [comment]
I want to note something here:

Even after the PR that @danielroe linked, I continued to have this issue. Then when I dove a bit deeper to create a reproduction I realised that the difference between the working version and my non-working version was the way that the `ipx` package was imported in the `.nuxt/dev/index.mjs` file. In the working version, the import path went like `"file:///Users/..."` where as the non-working version it was simply `"ipx"`. 

Trying to figure out where this was coming from, I did a bunch of things: (1) Removing the explicit `@nuxt/devtools` dependency from our `package.json` since it now automatically comes from nuxt (2) Copying over the `excludes` field from the auto generated nuxt `tsconfig` again to the project one since we overwrite/expand it, and (3) just went back-and-forth between versions 1.3.0, 1.4.0, and 1.6.0. By the end of this, the issue was fixed for me. 

I'm not sure which one of them ended up fixing it but maybe this will be helpful to someone 🤷
