### ISSUE TITLE
Lazy loading doesn't work on static site

### ISSUE THREAD

**Issue by 684efs3** [nuxt/image#127]
Lazy loading works on the development server, but not on the static site that is generated. I am using dynamically generated images.

**Comment by boltshauser** [comment]
I have a similar situation here with dynamic images where the images won't display after filtering.
Initially the images are displayed on the static site, but if I filter them and then reset the filter, the image path changes to the original filename e.g `https://domain/filename.jpg` instead of `https://domain/_image/8306ec.jpg` and I get a 404.

**Comment by boltshauser** [comment]
Sorry, it seems my issue is not related to lazy loading. It only happens on the deployed static site and not during dev.

**Comment by Bohreromir** [comment]
Can confirm, dev works as expected, but after nuxt generate and then start it wont work anymore

**Comment by Gompje** [comment]
@boltshauser, @Bohreromir →   I'm seeing the same thing, works during dev, even locally generated seems to work; but not on the server. what did you guys end up doing? not using this to display the images? or?

**Comment by Gompje** [comment]
I'm going to answer my own question: seems like using the undocumented feature `:lazy='false'` works as workaround; aka turning off the lazy loading

**Comment by pkpowell** [comment]
0.4.8 has resolved this for me
