### ISSUE TITLE
Nuxt Picture stretching image while Nuxt Image keeps the aspect ratio

### ISSUE THREAD

**Issue by Tragio** [nuxt/image#174]
Hello team 🙂 

I was trying Nuxt Picture and I noticed that it is stretching the image, while Nuxt image keeps the aspect ratio.

I created a [repo](https://github.com/Tragio/Nuxt-Image-Bug) that shows the same image in both components.

Thank you for the amazing work.

**Comment by ms-fadaei** [comment]
I have this issue too

**Comment by Yiddishe-Kop** [comment]
I have a similar issue.
I want the image to be 100% width, but auto height.

With `nuxt-img` I get what I expected. See screenshot:
![CleanShot 2021-02-06 at 9 10 01](https://user-images.githubusercontent.com/36875437/107127589-c8182580-68bf-11eb-932b-256288905f22.png)

But with `nuxt-picture` it doesn't work the same. it doesn't respect the images aspect ratio. See screenshot:
![CleanShot 2021-02-06 at 9 10 24](https://user-images.githubusercontent.com/36875437/107127619-fa298780-68bf-11eb-9b19-c0000a1cbd54.png)

**Comment by tanc** [comment]
In my site `nuxt-picture` doesn't stretch the image but it is resizing the elements it is positioned inside. I have a grid css based layout and the use of the div with class `sizer__responsive` is breaking the layout. To remove this I used:

```
.sizer__responsive {
  display: none !important;
}
```

I found that when the `nuxt-picture` element was used outside of the grid then I needed the `sizer__responsive` div, otherwise the images collapsed to no width and height.

Also specifying `responsive="false"` as a prop didn't seem to change the behaviour.

**Comment by dpschen** [comment]
As far as I understood this is the expected behaviour: 

> The image's width will be equal to width of parent element in DOM and its height calculates based on the aspect ratio. Forcing images to preserve aspect ratio will prevent layout shifting. If you want to resize the image all you need is changing the width using CSS.

_(from https://image.nuxtjs.org/components/nuxt-picture/)_

I got the same issue currently. I want to use the features of nuxt-picture in a place where I want the height of the parent define the image size.

Not sure if that makes sense since I thought that `nuxt-img` would behave similar to `<img />` and thus `nuxt-picture` similar to `<picture />`.

@tanc:

> Also specifying responsive="false" as a prop didn't seem to change the behaviour.

It seems like the nuxt-picture component currently doesn't feature the responive property. Was confused by this as well since it's stated differently in the documentation:


> `<nuxt-picture>` supports all available props of `<nuxt-img>` with these additional props.

**Comment by pi0** [comment]
Hi. Problems with `<nuxt-picture>` should be gone by image@0.4.0 and it behaves similar to nuxt-img. 

Since we no longer add additional styles and wrapper div that was required for placeholder support. (placeholder support will be added back as a wrapper component).
