### ISSUE TITLE
add `@load` event for images

### ISSUE THREAD

**Issue by pkpowell** [nuxt/image#212]
Is there an "on load" event that one could use to fade in images etc?
I tried adding `@load="imgLoaded"` to `<nuxt-image>` but `imgLoaded`is never called.

**Comment by pkpowell** [comment]
Great, thanks!

**Comment by madsh93** [comment]
@danielroe I am displaying an image with a dynamic source that changes on a button click, thus the page is already hydrated and therefore @load.native does not work.

Is it even possible to add placeholders for such situation? My issue is that theres a blank image for a second or two, when changing the src.

```js 
      <nuxt-img
        :src="
          imageLoading
            ? '/loading.svg'
            : `https://admin.kassebil.dk/assets/${images[selectedImage].color_image}`
        "
        width="620"
        @load.native="imageLoading = false"
      />
````

My other solution would be to fetch the images in the background when the page is finished loading, so that the images are loaded faster when the source is changed. But I don't think this is possible with Nuxt 2, or atleast I don't know how to.

**Comment by Vadimpioner** [comment]
> @danielroe I am displaying an image with a dynamic source that changes on a button click, thus the page is already hydrated and therefore @load.native does not work.
> 
> Is it even possible to add placeholders for such situation? My issue is that theres a blank image for a second or two, when changing the src.
> 
> ```js
>       <nuxt-img
>         :src="
>           imageLoading
>             ? '/loading.svg'
>             : `https://admin.kassebil.dk/assets/${images[selectedImage].color_image}`
>         "
>         width="620"
>         @load.native="imageLoading = false"
>       />
> ```
> 
> My other solution would be to fetch the images in the background when the page is finished loading, so that the images are loaded faster when the source is changed. But I don't think this is possible with Nuxt 2, or atleast I don't know how to.

found a solution to this problem?
