### ISSUE TITLE
Add default Alt from Source for SEO purpose and Accessibility 

### ISSUE THREAD

**Issue by ManasMadrecha** [nuxt/image#325]
## What is expected?
If the `alt` is not written, then by default some alt should be generated. The best way is to just add the `src` as the alt, as usually people keep the `src` SEO-friendly.

Something like this is needed:
```
return this.alt ? this.alt : this.src
```

## What is happening?
`alt` is `undefined`.

## Why needed?
1. For SEO purpose.
2. Accessibility 

## Further option to disable it

If possible, then a option can be added in `nuxtconfig.js`'s `image` object as to whether people want this feature enabled or disabled.

**Comment by ManasMadrecha** [comment]
@danielroe Of course, it's not the best practice, but it's better than having no alt name. As I mentioned above, the filename will only show as alt if, by mistake, we forget to add the alt name.

**Comment by pi0** [comment]
@ManasMadrecha  Alt is not supposed for helping search engine optimization but it is indicating an alternative text replacement ,when loading image is not possible and for screen readers. 

Auto generating `alt`  based on `src`, is not a good idea since search engines already use much better NLP algorithms based on filenames to imply and it only confuses them more and break A11Y/semantics.

Still if you really want to do it, can use either wrapper component or global `$alt` generator utility (example: https://codesandbox.io/s/hidden-flower-5kuj1?file=/plugins/alt.js)

**Comment by pi0** [comment]
PS: Adding warning when alt is not provided will be coming soon :) (https://github.com/nuxt/image/issues/315)

**Comment by ManasMadrecha** [comment]
That `$alt` utility is amazing. Thank you very much.
