### ISSUE TITLE
Allow setting simple view-width based "sizes" values

### ISSUE THREAD

**Issue by kara** [nuxt/image#645]
To reproduce:
1. Add nuxt/image to modules (in config, yarn add, etc)
1. Add nuxt/image instance with width and height set
1. Add a sizes property based on "vw" units

```
<nuxt-img src="cat.jpg" width="300" height="200" sizes="100vw" />
```

Expected behavior:
Image component has a `srcset` attribute with width-descriptors. The `sizes` attribute falls through to the <img> tag as is. 

Expected result:

```
<img src="cat.jpg" width="300" height="200" 
     srcset="cat.jpg?w=200 200w, cat.jpg?w=400 400w…" 
     sizes="100vw" />
```

Actual behavior:
The image doesn't render. An empty `srcset` attribute and an empty `sizes` attribute is generated. No `src` is generated. 

Actual result:
```
<img width="300" height="200" srcset sizes />
```

Suggested change:
The `sizes` attribute should support passing vw-based values directly to the underlying image tag. A generic `srcset` should be generated with common device sizes.

**Comment by nomadoda** [comment]
Duplicate issue https://github.com/nuxt/image/issues/469

**Comment by Baroshem** [comment]
@danielroe I did some investigation and I have found a solution for the sizes not being generated.

Because there was no sizes, there was also no srcset because it was using it to correctly create a srcset list.

Let me know if that was the idea with this task.

<img width="1159" alt="image" src="https://github.com/nuxt/image/assets/37120330/85244ac8-1ce5-44f2-b1cf-4a9ed71245ed">
