### ISSUE TITLE
Uncaught TypeError: Cannot set properties of null (setting 'src') at img.onload - using Sanity provider

### ISSUE THREAD

**Issue by toddpadwick** [nuxt/image#708]
This error occurs on every nuxt-img on my site.
Here is an example of one of these images:
```
<nuxt-img v-if="entry.heroImage?.url && entry.heroImage?.asset?._ref" class="listed-entry__visual__image" provider="sanity" :src="entry.heroImage.asset._ref" :width="entry.heroImage.width" :height="entry.heroImage.height" :placeholder="$urlFor(entry.heroImage.asset).width(100).quality(25).blur(100).auto('format').url()" sizes="xxs:100vw md:50vw lg:33.33vw xl:500px" loading="lazy" :alt="entry.title"/>
```

```
onMounted(() => {
      if (placeholder.value) {
        const img = new Image();
        img.src = mainSrc.value;
        img.onload = () => {
          imgEl.value.src = mainSrc.value;
          placeholderLoaded.value = true;
        };
      }
    });
```

Using Nuxt 3.0.0
Using nuxt-img with sanity provider

**Comment by zswilhelm** [comment]
Uncaught TypeError: Cannot set properties of null (setting 'src') error 
when use placeholder parameter in nuxt-img
example:
<nuxt-img src="/image.png" placeholder />

**Comment by elizabthpazp** [comment]
any solution? the same thing happens to me

**Comment by aeadedoyin** [comment]
I discovered it's an issue with the `nuxt-img` component, it uses `this.$refs.img` to reference the img element [on this line](https://github.com/nuxt/image/blob/075d1c3763e3b723096cba3ad56846e4e42fbbf4/src/runtime/components/nuxt-img.vue#L89).
Calling `this.$refs.img` directly `onMounted` for a complex component like that is usually not always effective.

Two approaches that worked:
1. The `nuxt-img` component should leverage `this.$nextTick(...)`. The this.$nextTick method schedules a callback to be called after the next DOM update cycle. This ensures that the img element has been fully rendered before accessing it using this.$refs.img
2. or Use `this.$el` since the root element is the `img` tag and root elements in components are always available no matter how complex the component can be.

**Comment by aeadedoyin** [comment]
@toddpadwick I don’t think it's peculiar to only Sanity provider, other providers are affected,



I did some debugging and discovered it's an issue with the `nuxt-img` component, it uses `this.$refs.img` to reference the `img` element [on this line](https://github.com/nuxt/image/blob/075d1c3763e3b723096cba3ad56846e4e42fbbf4/src/runtime/components/nuxt-img.vue#L89).
Calling `this.$refs.img` directly on `mounted` for a complex component like that is usually not always effective.

Two approaches that worked:
1. The `nuxt-img` component should leverage `this.$nextTick(...)`. The `this.$nextTick` method schedules a callback to be called after the next DOM update cycle. This ensures that the `img` element has been fully rendered before accessing it using `this.$refs.img`
2. or Use `this.$el` since the root element is the `img` tag and root elements in components are always available no matter how complex the component can be.

I would have created a PR for this but I doubt the team is supporting this Nuxt 2 version of `nuxt-img` anymore, given the number of PRs without even a comment. 

For now anyone that has this error just ignore or migrate to Nuxt 3

**Comment by Baroshem** [comment]
Closing as the solution was provided in the comments.
